#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define THREEDIM 3
#define XDIR 0
#define YDIR 1
#define ZDIR 2
#define HARDWALL_BC 1
#define SOFTWALL_BC 2
#define CONTACT_HERTZ 1
#define MAXSPECIES 5
#define MAXBRIDGES 6
#define MAXBONDS 6

#define BP_NP0 1
#define BP_NP1 3
#define BP_NP2 5
#define BP_NP3 10

#define NTP_TEMP 293
#define fourbythree 1.3333333333
#define half 0.5
#define PI 3.141592654
#define three 3.0
#define two 2.0
#define one 1.0
#define four 4.0
#define twobyfive 0.4
#define fourth 0.25
#define zero 0.0
#define TINYVAL 1e-20
#define BIGVAL 1e20
#define RUNIV 8.314
#endif
