#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define THREEDIM 3
#define XDIR 0
#define YDIR 1
#define ZDIR 2
#define HARDWALL_BC 1
#define SOFTWALL_BC 2
#define CONTACT_HERTZ 1
#define MAXSPECIES 1
#define MAXBRIDGES 8
#define MAXBONDS 4
#define MAXILBONDS 8

#define BP_TYPES 29
#define BP_NP0 1
#define BP_NP1 2
#define BP_NP2 3
#define BP_NP3 4
#define BP_NP4 5
#define BP_NP5 6
#define BP_NP6 7
#define BP_NP7 8
#define BP_NP8 9
#define BP_NP9 10
#define BP_NP10 10
#define BP_NP11 16
#define BP_NP12 32
#define BP_NP13 36
#define BP_NP14 72
#define BP_NP15 80
#define BP_NP16 8
#define BP_NP17 12
#define BP_NP18 12
#define BP_NP19 32
#define BP_NP20 40
#define BP_NP21 8
#define BP_NP22 10
#define BP_NP23 12
#define BP_NP24 32
#define BP_NP25 40
#define BP_NP26 10
#define BP_NP27 12
#define BP_NP28 16

#define NTP_TEMP 293
#define fourbythree 1.3333333333
#define half 0.5
#define PI 3.141592654
#define three 3.0
#define two 2.0
#define one 1.0
#define four 4.0
#define twobyfive 0.4
#define fourth 0.25
#define zero 0.0
#define TINYVAL 1e-20
#define BIGVAL 1e20
#define RUNIV 8.314
#define sqtwo 1.414213562373
#define sqthree 1.73205080757
#endif
